### ISSUE TITLE
"-Bt" prints an extra line at the top

### ISSUE THREAD

**Issue by wjandrea** [alecthomas/pawk#15]
E.g.

```
$ printf 'foo\nbar' | pawk -Bt

foo
bar
```

I was just trying out pawk when I noticed this.

**Comment by alecthomas** [comment]
"t" is the input text up until that point, so at the beginning (`-B`) it will be empty. If you use `-E` it will work as expected.

That's probably just a documentation issue...

**Comment by wjandrea** [comment]
Ah, I see, so `pawk -Bt` is equivalent to `pawk -B '""' ''` or `awk 'BEGIN {print} //'`.

Yes, the documentation seems to say the `expr` is required:
```
Usage: cat input | pawk [<options>] <expr>
```
So I guess I would expect it to error in that case, but anyway, nbd for me personally.

**Comment by sebhaase** [comment]
Please close this issue.

**Comment by wjandrea** [comment]
@sebhaase The documentation is still wrong, though I'm not concerned, so I'll leave it to Alec whether they want close this.

**Comment by alecthomas** [comment]
Documented!
