### ISSUE TITLE
I broke pawk 0.8.0 😱

### ISSUE THREAD

**Issue by jrjsmrtn** [alecthomas/pawk#22]
I only tested _Poetry build_ with my patch to `pyproject.toml` but made no further tests.

I added no `scripts` entries, thus no `pawk` script is installed 😕. Moreover, the `bin` directory containing `python` and `hermit` binaries is unnecessary.

I'll have a look and submit another PR...

**Comment by alecthomas** [comment]
I _think_ I fixed it in 0.8.1, give it a shot.

**Comment by jrjsmrtn** [comment]
Yep, the script is now installed. :-)

The following files and folders can be removed, though:
- `bin/`
- `MANIFEST.in`
- `__init__.py`
- `pawk`
- `setup.py`

I added an explicit `packages` entry in my latest patch, but I'm not certain it's necessary:
```
packages = [
    { include = "pawk.py" },
]
```
The versions are not synchronized between `pyproject.toml` and `pawk.py`. I'm aware of the [pyproject-bumpversion](https://pypi.org/project/poetry-bumpversion/) plugin to handle such a sync.

**Comment by alecthomas** [comment]
`bin/` is part of [Hermit](https://cashapp.github.io/hermit/) which is used to manage the tooling, but I'll nuke the rest.
