### ISSUE TITLE
Is there a variable holding the header line fileds?

### ISSUE THREAD

**Issue by dclong** [alecthomas/pawk#7]
i.e., column names? I want to select columns by name.

**Comment by alecthomas** [comment]
Not built-in, no, but that's an interesting idea. You're thinking of input where the first row is the column headers, like so?

```
count name
12 bob
34 fred
```

**Comment by alecthomas** [comment]
Implemented in v0.6.4 (fa5a5965862d080873ed23df9183bd7f6fa7fd2d).
