### ISSUE TITLE
Add a option to keep the header row

### ISSUE THREAD

**Issue by dclong** [alecthomas/pawk#9]
The newly added feature `-H` is great! However, it is even better if a user is allowed to process the header row as well. For example, in your example of 
```
count name
12 bob
34 fred
```
`pawk -H '"%s is %s" % (name, count)' < input.txt` produces the following results. 
```
name is count
bob is 12
fred is 34
```
Or at least, there should be an option allowing users to do so. One simple use case is to use pawk to extract columns from a text file. Users often want to keep the header row in this situation.

**Comment by alecthomas** [comment]
The header can be printed with:

```
pawk -H -B '"name is count"' '"%s is %s" % (name, count)' < input.txt
```

Do you have a use-case where this wouldn't solve the problem?

Outside very simple cases, having the header as part of the input will just make life more difficult, as you have to explicitly check whether your input is the header or a normal row, and do different things in either case. eg. the above would become:

```
pawk -H '"name is count" if n == 1 else "%s is %s" % (name, count)' < input.txt
```
